### ISSUE TITLE
how to connect with you ?

### ISSUE THREAD

**Issue by elmagekmosaad** [tuberboy/freebasics#1]

**Comment by tuberboy** [comment]
@elmagekmosaad do you have any questions?

**Comment by elmagekmosaad** [comment]
> @elmagekmosaad do you have any questions?

i need your help in another thing

**Comment by tuberboy** [comment]
> > @elmagekmosaad do you have any questions?
> 
> i need your help in another thing

Please let me know what kind of help you need. Share your ideas or feedback.

**Comment by elmagekmosaad** [comment]
> > > @elmagekmosaad do you have any questions?
> > 
> > 
> > i need your help in another thing
> 
> Please let me know what kind of help you need. Share your ideas or feedback.

private help i can't write it in public
if you want to help me chat with me on telegram at : elmagekmosaad
or tell me where i can chat with you
